web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  extends:
    file: common.yml
    service: common
  command: "/bin/sh -c 'while true; do sleep 1; done'"
db:
  image: "mysql:5"
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=123456"
    - "MYSQL_DATABASE=myweb"
